### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by Tolriq** [ohmae/mmupnp#18]
Hi,

First thanks for the library it works great, is small and did I say it works great ? :)

May I suggest an enhancement to action invoke exceptions?
Returning "" is not very helpful and since the Javadoc is in Japanese hard to find the ,true version without looking more.

https://github.com/ohmae/mmupnp/blob/master/lib/src/main/java/net/mm2d/upnp/Action.java#L313
https://github.com/ohmae/mmupnp/blob/master/lib/src/main/java/net/mm2d/upnp/Action.java#L423

Since Map have a nice toString() method just using result.toString() instead of "" would help a lot and prevent consumers to always add the ,true and parse the result to display the error.

**Comment by ohmae** [comment]
Thanks for the suggestion, I fixed it. https://github.com/ohmae/mmupnp/commit/9ad14f8b96730a74496e32acaabceae20ef9fe79

**Comment by Tolriq** [comment]
Thanks a lot, do you have an ETA for next public release? I'd like to go in beta in my app with your library ASAP to find potential issues :)

**Comment by ohmae** [comment]
Umm. I planned to release a big feature, but it seems better to release it before that.
I will release 1.7.2 now.

**Comment by ohmae** [comment]
I released 1.7.2

**Comment by Tolriq** [comment]
Thanks was fast :) Tested and working.
