### ISSUE TITLE
ConcurrentModificationException crash

### ISSUE THREAD

**Issue by Tolriq** [ohmae/mmupnp#19]
So now the app is in prod and more users will use and reveal issues :)

See attached logs, 

Synchronized on methods for lists is usually problematic, for this kind of listeners, with much more iteration than adds, CopyOnWriteArrayList is a better and more robust solution.

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at net.mm2d.upnp.DiscoveryListenerList.onDiscover(DiscoveryListenerList.java:38)
       at net.mm2d.upnp.ControlPoint$4.run(ControlPoint.java:533)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by ohmae** [comment]
I think that this cause is calling `ControlPoint#addDiscoveryListener()` or `ControlPoint#removeDiscoveryListener()` on `DiscoveryListener#onDiscorver()`.
Can not you avoid it?

I think CopyOnWriteArrayList is good solution but it is too costly... 
Please let me think a bit.

**Comment by ohmae** [comment]
Since add / remove are not called so frequently, I decided that cost is not a problem.
(I misunderstood about CopyOnWriteArrayList. I had thought that the cost of iteration was also high. :sweat_smile:)
I fixed it. https://github.com/ohmae/mmupnp/commit/681373e2f81c1c8e853a8af1f8eb15079ae2186d
And I released Ver.1.8.1

**Comment by Tolriq** [comment]
Yep the CopyOnWriteArrayList is perfect for listeners registration ;)

About the calls I can't remove them, it's hard to know how it happens but I suppose that the issue is caused by my reconnect to host code.
Add listener, start discovery, when correct host is found remove listener, the CP is not shutdown since I'll use it just after. If there's other hosts being discovered during the remove -> crash.
This is a normal use case.

Anyway thanks for the quick fix. Since you have made more changes to the lib I'll do more tests before pushing to prod :)

**Comment by Tolriq** [comment]
In prod and no more crashes :)

Thanks.
