### ISSUE TITLE
[Question] UPnP devices not found

### ISSUE THREAD

**Issue by Tolriq** [ohmae/mmupnp#22]
Hi again :)

I'm trying to debug one user who no more see his upnp renderers in my application.
Strangely enough he can see them in DMSExplorer.

I have tons of users including me where the library works perfectly.

Do you have any idea what could be specific inside DMS explorer?
Maybe there's some reflection inside the library an there's need for specific proguard rules?
Or you are checking exception classname to handle special cases and they are renamed?

I'm a little out of idea and since I can't replicate it's quite hard to debug.

**Comment by ohmae** [comment]
Sorry, I have no idea.
There is no proguard rules to use this library. and I’m not doing any special handling in DMS Explorer.
Have you confirmed what the difference is?
https://github.com/ohmae/DmsExplorer

**Comment by Tolriq** [comment]
So after tons of tests it seems on his network device do not respond to the first search query and require multiple sends. (You do that every 5 seconds in DMS).

This is strange but well it works. Maybe there's some race condition in the library and first search packet are not sent if start and search are too close?

**Comment by ohmae** [comment]
Certainly, while `start()` is starting socket on another thread, `search()` calls socket on the call thread.
However, it is strange that the problem occurs only with that device. If the packet could not be sent, other devices should not respond as well.

**Comment by Tolriq** [comment]
Actually there is multiple devices he just talked about one :) But with logs when it works I see all the others :)

I do call start and search on 2 different threads since search on main thread is forbidden so there's still a delay between to start the other thread seems no enough in some case.

BTW search sending packets on the calling thread is a relatively strange behavior of the library since it ca do network on main thread and crash. Since there's already all threading model, should maybe be called in a thread too.

**Comment by ohmae** [comment]
I know that I can not call from the main thread in Android.
But this library is not made for Android only nor is it just a `ControlPoint#search()` problem.
I'll consider what should be the thread policy for this whole library.

**Comment by Tolriq** [comment]
Yep there's issues with shutdown and other places.

But to be honest your library is wonderful as work perfectly for it's job and in a small and efficient way.
Lot's of people use Cling but your library can replace it easily and better if not needing the server part.

You could gain a tons of users with just some pushing on the main library listing sites.

To be perfect it would just be nice to have English JavaDocs and proper threading so that consumers do not have to spawn threads that you already have (costly operation).

Nice things to have would be, proper logging interface so that consumer could get the logs and use them, and some submodules to help with common things, like CDS from DMS.

**Comment by ohmae** [comment]
It has been a lot late. Fixed a thread contention issue.
