### ISSUE TITLE
ProperThreadPool with Java

### ISSUE THREAD

**Issue by Tolriq** [ohmae/mmupnp#23]
A sample Kotlin proper Scaling thread pool implementation that handle caching, and growing as needed.

[ScalingThreadPool.zip](https://github.com/ohmae/mmupnp/files/2305699/ScalingThreadPool.zip)

Some associated tests, (not fully usable as using a more complex version of that code to handle thread naming and priorities but giving a proper start to see the problems with the different queues in default implementation.

```
@Test
    fun getActiveCount() {

        ignoreOnContinuousIntegration()
        val executor: ScalingThreadPoolExecutor = ScalingThreadPoolExecutor.newScalingThreadPool(1, 3, 5, "Test") as ScalingThreadPoolExecutor

        var cdl = CountDownLatch(2)

        assertEquals(0, executor.activeCount)
        executor.execute {
            cdl.countDown()
            Thread.sleep(1000)
        }
        executor.execute {
            cdl.countDown()
            assertTrue(Thread.currentThread().name.startsWith("Test"))
            Thread.sleep(5000)
        }

        cdl.await(5, TimeUnit.SECONDS)
        assertEquals(2, executor.activeCount)
        assertEquals(2, executor.poolSize)
        Thread.sleep(1500)
        assertEquals(1, executor.activeCount)
        Thread.sleep(5000)
        assertEquals(0, executor.activeCount)
        assertEquals(1, executor.poolSize)

        cdl = CountDownLatch(3)
        executor.execute {
            cdl.countDown()
            Thread.sleep(1000)
        }
        executor.execute {
            cdl.countDown()
            Thread.sleep(1000)
        }
        executor.execute {
            cdl.countDown()
            Thread.sleep(1000)
        }
        executor.execute { Thread.sleep(1000) }

        cdl.await(5, TimeUnit.SECONDS)
        assertEquals(3, executor.activeCount)
        assertEquals(3, executor.poolSize)
        Thread.sleep(1250)
        assertEquals(1, executor.activeCount)
        assertEquals(3, executor.poolSize)
        Thread.sleep(5250)
        assertEquals(1, executor.poolSize)

        executor.shutdownNow()
    }

```

**Comment by ohmae** [comment]
:+1:

**Comment by Tolriq** [comment]
@ohmae Why close?

As explained current implementation of ThreadPool can't have more than 1 active thread for the ParallelExecutor

See following test that will fail with current setup. 2nd thread should run as the minimum size you set up is 2, yet it won't until thread 1 is ended.

```
    @Test
    public void executeInParallel_multipleThreads() throws InterruptedException {
        final ThreadPool threadPool = new ThreadPool();

        final CountDownLatch cdl1 = new CountDownLatch(1);
        AtomicInteger value = new AtomicInteger(0);
        threadPool.executeInParallel(() -> {
            value.set(1);
            cdl1.countDown();
            try {
                Thread.sleep(5000);
            } catch (InterruptedException ignore) {
            }
        });
        cdl1.await(1, TimeUnit.SECONDS);
        assertEquals(1, value.get());

        final CountDownLatch cdl2 = new CountDownLatch(1);
        threadPool.executeInParallel(() -> {
            try {
                value.set(2);
                cdl2.countDown();
                Thread.sleep(5000);
            } catch (InterruptedException ignore) {
            }
        });
        cdl2.await(1, TimeUnit.SECONDS);
        assertEquals(2, value.get());
    }
```

**Comment by ohmae** [comment]
I was again misunderstanding.
Since I still need time before I get to the correct answer, I will temporarily use FixedThreadPool.

**Comment by Tolriq** [comment]
I'm sorry that I currently do not have more time to properly made a PR :(

The 3 classes I gave you is a well working fully tested and in production in very large app since a very longtime converting to Java should be easy.

I'll probably have more time after 2 weeks.

**Comment by ohmae** [comment]
I solved in this way  https://github.com/ohmae/mmupnp/commit/68bd9a676e769b6b45b4e269ff6f2e542282c82d
I think that this is equivalent to your sample. And I think this is a simpler solution.

**Comment by Tolriq** [comment]
As long as you are sure your tests are OK, implementation is a detail, I was just pointing that the 2 previous ones had flaws and require attention. (And thanks for doing it :) )

Personally having a single class that does Queue and RejectedExecutionHandler at the same time makes things complicated to understand (passing a param named queue to a RejectedExecutionHandler  is hard to read) and in the end require 10 times more boiler code, but it's entirely your choice.
