### ISSUE TITLE
Update Kotlin StdLibs

### ISSUE THREAD

**Issue by eakteam** [ohmae/mmupnp#27]
First off thanks for this great and fast libs. I have just moved out 2 days before from cling to using this. It's great work, but for us who are very strict to smallest app possible it will be great if you update the Kotlin STD to kotlin-stdlib-jdk8

**Comment by ohmae** [comment]
Umm... I mainly assume to use this library on Android.
In Android, if use kotlin-stdlib-jdk8, we need API level 24 or higher.
I think it's too early to make minSdkVersion to 24.

**Comment by eakteam** [comment]
Hi @ohmae . I am using it for Android too. My minimum API is 16, i use jdk8 and everything is going fine. It have no restriction what jdk you will use. But jdk8 is better if you choose to use. I am testing your lib in my app forcing it to use jdk8 and everything is working fine.

This is my app https://play.google.com/store/apps/details?id=com.eakteam.networkmanager.pro and i have implemented your lib. It's great. The using case is only for Device discovery.

Here you have a promo code to use it for free. Thanks for your work.

PS. You should update to jdk8 :D :D still.

Promo : NLNLW9U5E364JVDSRQUV2KQ

**Comment by eakteam** [comment]
Also if you want to see how your lib is performing in my app, please download it using the promo code and join BETA. Because i will publish to production some days later

**Comment by Tolriq** [comment]
stdlib jdk8 provide nearly nothing except some future things that are not used here and so have no impact

Using Java 1.8 level in Android is OK except some very rare things when using Long or Char compare and a few things like that and R8 1.5 will handle this (So with Android AGP 3.5)

In all cases whatever version used R8 / Proguard will end up with the same APK size ;)

**Comment by eakteam** [comment]
@Tolriq i understand you and you'r almost very right ! But it cost nothing just to move from jdk7 to jdk8, it is just a very small change in gradle. I am using R8 too and in very very agresive way. But sometimes when i make some checks to see app dependencies, i am also seeing jdk7 from this lib. This lib is great comparing to cling which i used before. It is using Kotlin, gradle project, new things and without many dependencies. So for all the libs out there for UPnP/DLNA scanning (without being able to create service) this is the best.
Anyway this is just my request for jdk8, is your wish if you want it to add or not, but it have no impact as you said.

Anyway it is better to use new things.
Sorry for my low English, hope to be understandable.
Best Regards, keep up good work

**Comment by Tolriq** [comment]
Jdk8 contains jdk7 + a few things. This does not impact your APK size a bit that this library is JDK7.

But adding JDK8 in the lib would add a few bytes to all people that does not use R8 / proguard for 0 gain.

This is not my library and my call, but your request would not change anything to your app size.

**Comment by eakteam** [comment]
@Tolriq , @ohmae  i don't know who is developing this but i think it's Ohmae ? Soon in the public release (some days later) this lib will be promoted as main "thing" about UPnP/DLNA scanner. Great work guys.
In my gradle settings, i am forcing it to use jdk8 in my case, it's your choice if you will add it directly.
Best Regards

**Comment by eakteam** [comment]
@Tolriq thanks for your reply. I understand you well. Yes your explanation is right. Just you know, when programming it is little disturbing to see many dependencies coming from many libs :D :D . I am not saying that jdk8 will make things better. Just it will look better. Best Regards

**Comment by Tolriq** [comment]
https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jdk8/build.gradle :)

As I said JDK8 is on top of JDK7 so JDK8 include JDK7 in all cases, adding JDK8 here won't remove JDK7 but add new things not needed for other consumers.

**Comment by eakteam** [comment]
@Tolriq i see. Thanks for making me understand it better too ! Anyway i am using some things that cannot be used with jdk7, but for this lib you'r right, jdk8 maybe is not needed.

**Comment by ohmae** [comment]
@eakteam @Tolriq Thank you for the good discussion.
I was able to know a lot of things :)

**Comment by Tolriq** [comment]
Thanks again for the lib, for info I'm in prod since today with 3.0 and coroutines so far no issues.

**Comment by eakteam** [comment]
Thanks from me too. I don't have any issue too ! It is working OK.
