### ISSUE TITLE
Number of threads for 3.0

### ISSUE THREAD

**Issue by Tolriq** [ohmae/mmupnp#29]
It seems 3.0 creates really a tons of threads like 12 on a 8 core device.
Are so much threads really necessary? Specially when dealing with coroutines?

**Comment by ohmae** [comment]
I think some extent threads is necessary for network io even if use coroutines.
It may be possible to reduce client threads, but it is difficult to reduce server threads.
For example, it is likely to be able to reduce thread if use MulticastChannel, but it can not be used yet.

**Comment by Tolriq** [comment]
Ok thanks :(

Do you think you can release a quick 3.0.2 with the other fix so I can push to prod?

**Comment by ohmae** [comment]
I released 3.0.2

**Comment by Tolriq** [comment]
Thanks.
