### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by Tolriq** [ohmae/mmupnp#35]
Hi :)

Once again thanks for this lib, Jcenter will soon shutdown so it would be nice if you could publish this and logs to mavencentral so that we have no issues after May.

Regards,
Tolriq

**Comment by ohmae** [comment]
I'm working on registering to maven central right now... It's not easy...

**Comment by Tolriq** [comment]
Yes I've seen the signature stuff and everything :( But thanks for doing it :)

**Comment by ohmae** [comment]
Done. https://search.maven.org/artifact/net.mm2d.mmupnp/mmupnp

**Comment by Tolriq** [comment]
Thanks
