### ISSUE TITLE
[Question] ControlPoint.search argument “st” does’t effect?

### ISSUE THREAD

**Issue by yamatakau08** [ohmae/mmupnp#37]
I called **ControlPoint.search(“urn:schemas-upnp-org:service:ContentDirectory:1”)** to get DMS devices.
But after that, **ControlPoint.deviceList**  has the Wi-Fi Access Point that does not support DMS function.
Could you support  what is wrong?

My code is the following.
```
   private val cp: ControlPoint = ControlPointFactory.create().also {
        it.addDiscoveryListener(discoveryListener({ onDiscoverCallback() }, { onLostCallback() }))
        it.initialize()
        it.start()

       // M Search to get DMS devices
        it.search("urn:schemas-upnp-org:service:ContentDirectory:1")

        // to get the response for search
        Thread.sleep(2000)
    }

    private fun onDiscoverCallback() {}
    private fun onLostCallback() {}

```

Wi-Fi Access Point serviceList part in device xml
```
<serviceList>
<service>
<serviceType>urn:schemas-wifialliance-org:service:WFAWLANConfig:1</serviceType>
<serviceId>urn:wifialliance-org:serviceId:WFAWLANConfig1</serviceId>
<SCPDURL>/x_wfawlanconfig.xml</SCPDURL>
<controlURL>/control?WFAWLANConfig</controlURL>
<eventSubURL>/event?WFAWLANConfig</eventSubURL>
</service>
</serviceList>
```

**Comment by ohmae** [comment]
ControlPoint is accepting all discovered devices.
The search method only throws a search packet and does not limit which device is found.
Filter the deviceList, if you want to limit the device type.
Or use the [setSsdpMessageFilter](https://ohmae.github.io/mmupnp/dokka/mmupnp/net.mm2d.upnp/-control-point/set-ssdp-message-filter.html) method, if you want to limit the devices that ControlPoint accepts.

**Comment by yamatakau08** [comment]
> The search method only throws a search packet and does not limit which device is found.

I understand that.

> Filter the deviceList, if you want to limit the device type.

Thank you for your advice. I’ll apply this.

> Or use the setSsdpMessageFilter method, if you want to limit the devices that ControlPoint accepts.

If you are available, for later study, could you give me the sample code which filter the device has the service type urn:schemas-upnp-org:service:ContentDirectory:1 with setSsdpMessageFilter
I checked the manual and dug into the source code.
Unfortunately, I couldn’t imagine how I should write the code.

**Comment by ohmae** [comment]
e.g.
```kotlin
ControlPointFactory.create().also {
    it.setSsdpMessageFilter { ssdp->
        ssdp.type == "urn:schemas-upnp-org:service:ContentDirectory:1"
    }
}
```

**Comment by yamatakau08** [comment]
I appreciate you providing the sample code.
