### ISSUE TITLE
[Question] cp.search finds the devices, disconnect Wi-Fi, call cp.search, cp.deviceList keeps the device data.

### ISSUE THREAD

**Issue by yamatakau08** [ohmae/mmupnp#40]
Both Wi-Fi and mobile data are available on mobile
mmupnp cp.search() finds the devices.
then disconnect Wi-Fi , mobile data is only available.
In that status, call cp.search().
has Exception `W/SsdpServerDelegate: java.io.IOException: sendto failed: ENETUNREACH (Network is unreachable)`
I understand this Exception.
But cp.deviceList keeps still the devices data.
Is this mmupnp spec?

In that status, I expect the onLost method of ControlPoint.DiscoveryListener is called with no devices data.
With onLost call back, I want to clear the devices in the list view.

**Comment by ohmae** [comment]
mmupnp does not monitor reachability; if no update is made within the max-age time, onLost will be called.

**Comment by yamatakau08** [comment]
Thank you for the answer.

>  mmupnp does not monitor reachability
I understand the spec of mmupnp.

after call cp.search(), mmupnp puts out the log the following.

```
2022-05-04 19:07:25.980 31903-32653/com.example.myavremote D/SsdpServerDelegate: send from /192.168.0.40/24 [/192.168.0.255]:
2022-05-04 19:07:25.980 31903-32653/com.example.myavremote D/SsdpServerDelegate: M-SEARCH * HTTP/1.1
2022-05-04 19:07:25.980 31903-32653/com.example.myavremote D/SsdpServerDelegate: HOST: 239.255.255.250:1900
2022-05-04 19:07:25.980 31903-32653/com.example.myavremote D/SsdpServerDelegate: MAN: "ssdp:discover"
2022-05-04 19:07:25.980 31903-32653/com.example.myavremote D/SsdpServerDelegate: MX: 1
2022-05-04 19:07:25.980 31903-32653/com.example.myavremote D/SsdpServerDelegate: ST: ssdp:all
...
2022-05-04 19:07:25.982 31903-32653/com.example.myavremote W/SsdpServerDelegate: java.io.IOException: sendto failed: ENETUNREACH (Network is unreachable)
...
```

I reach to the conclusion to handle the exception.
`W/SsdpServerDelegate: java.io.IOException: sendto failed: ENETUNREACH (Network is unreachable)`

Unfortunately my code the following can't get the that exception after cp.search().
Could you support me why my code can't  get the exception?

```
 try {
     cp.search()
 } catch(e: Exception) {
    // can't get the following Exception
    // W/SsdpServerDelegate: java.io.IOException: sendto failed: ENETUNREACH (Network is unreachable)
 }
```

**Comment by yamatakau08** [comment]
Adding `finally` block may solve my concern.
But I want to get the exception message in this case.
I'm waiting for you advice.

**Comment by ohmae** [comment]
Since interface changes are assumed to be handled by the user,
there is no mechanism to detect such errors on the user side.

**Comment by yamatakau08** [comment]
Thank you for the answering.
> there is no mechanism to detect such errors on the user side.
I understand that.

>   if no update is made within the max-age time, onLost will be called.
I grep the maxAge in mmupnp
```
 /tmp [124]> find . -type f | xargs grep -i "maxAge.*="
grep: ./fseventsd-uuid: Permission denied
./mmupnp/mmupnp/src/test/java/net/mm2d/upnp/empty/EmptySsdpMessageTest.kt:        assertThat(message.maxAge >= 0).isTrue()
./mmupnp/mmupnp/src/main/java/net/mm2d/upnp/empty/EmptySsdpMessage.kt:    override val maxAge: Int = 0
./mmupnp/mmupnp/src/main/java/net/mm2d/upnp/internal/message/SsdpMessageDelegate.kt:            maxAge = 0
./mmupnp/mmupnp/src/main/java/net/mm2d/upnp/internal/message/SsdpMessageDelegate.kt:            maxAge = message.parseCacheControl()
./mmupnp/mmupnp/src/main/java/net/mm2d/upnp/internal/message/FakeSsdpMessage.kt:    override val maxAge: Int = Integer.MAX_VALUE
```

maxAge seems to be **val** variable, Can I change the maxAge from my program?

If I could change maxAge from my program, can I archive to clear the device list in LIstView with Non Wi-Fi connecting?
On the other hand, during Wi-Fi connecting and mmupnp already finds the all devices, onLost will be called?

Could you teach me about that point.

**Comment by ohmae** [comment]
It's what the device notifies.
Please read the specifications.
https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf

**Comment by yamatakau08** [comment]
> It's what the device notifies.
Thank you for teaching.

I close this issue.
