### ISSUE TITLE
Option to set headers

### ISSUE THREAD

**Issue by Greeeeyyyss** [ohmae/mmupnp#41]
I created this issue but this is more of a question on how to set headers if there's an option to before invoking an action. 

For example on below code, it sets a URI for SetAVTransportURI action but the URI requires a header for authorization to be able to play or stream it properly.

```
val action = mediaServer.findAction("SetAVTransportURI")
action?.invoke(
    mapOf(
        "InstanceId" to "0",
        "CurrentURI" to ""
        )
)
```
Thank you for your hard work, really easy to use and helpful in integrating upnp in the app!

**Comment by ohmae** [comment]
What is "a header for authorization"?

**Comment by Greeeeyyyss** [comment]
Sorry I was not clear, it will be an access token required to play a stream url. I was wondering if the invoke action could be setup like [this](https://developer.android.com/reference/android/media/MediaPlayer#setDataSource(android.content.Context,%20android.net.Uri,%20java.util.Map%3Cjava.lang.String,%20java.lang.String%3E)) how it is in Android and could pass in headers somehow.

Android sample:
`this.standardPlayer?.setDataSource(
                            context,
                            Uri.parse(song.playableItem?.playStringURL),
                            mapOf("Authorization" to "OAuth <accesstoken here>")
                        ) `

**Comment by ohmae** [comment]
There is no such feature in this library. It's out of UPnP specs

**Comment by Greeeeyyyss** [comment]
Hmm I see, thanks. Will close this then.

**Comment by Greeeeyyyss** [comment]
Hi again, I have forked this library and created a branch with the changes I have in my mind. I also was trying to use the forked version as a dependency in gradle but unfortunately I had a [build error](https://jitpack.io/com/github/Greeeeyyyss/mmupnp/feat~option-to-set-header-v3.0.0-alpha3-g109e085-229/build.log) using jitpack. 

Would you have an idea about this issue?
> Cannot perform signing task ':xml:signMavenJavaPublication' because it has no configured signatory`

Anyway, if you also have time let me know what you think about these changes or if you want me to create a pull request. 

Your response is much appreciated!

PR: [option to set headers](https://github.com/Greeeeyyyss/mmupnp/pull/1)

**Comment by Tolriq** [comment]
You PR set the headers for mmUPnP to talk to the control point. This won't make the control point use any header to then access the url set on `SetAVTransportURI`.

There's nothing in the UPnP spec to pass headers for the control point to use to access the content when playing it. If you need that you need to proxy.

**Comment by Greeeeyyyss** [comment]
O that's unfortunate. Thank you for the clarification!

**Comment by ohmae** [comment]
@Greeeeyyyss 
You're free to fork this and do whatever you want, but I'd suggest you base on the release version since the develop branch contains changes that can't be released yet. https://github.com/ohmae/mmupnp/tree/support/3.x.x
I don't know much about Jitpack, but if you're going to publish your version, please change the groupId.
For build errors, How about referring to the following?
https://docs.gradle.org/current/userguide/signing_plugin.html
